#!/usr/bin/env bash

# npm run babel -- --plugins transform-react-jsx

# -p means no error when trying to create a pre-existing bin/
mkdir -p bin

# flow transform
# npm run babel -- --presets flow index.js
npm run babel -- js/ -d bin

# clientside require
npm run browserify -- bin/index.js -o bin/bundle.js
